### PR TITLE
add support for relative paths in sjs command

### PR DESCRIPTION
**Pull request by gkovacs**
fixes https://github.com/sweet-js/sweet.js/issues/648

### CODE REVIEW

**Comment by gabejohnson** [comment]
@disnet Should this be fixed in the loader?

**Comment by disnet** [comment]
Yeah, I would have expected the loader to resolve relative paths. @gkovacs could you investigate why the loader is doing it wrong?

**Comment by disnet** [comment]
@gkovacs have you had a chance to look at the loader? Need any pointers?

If you don't have time no worries, I'll probably look into this soon.

**Comment by gkovacs** [comment]
@disnet Sorry I don't use sweet.js anymore, I'll leave it to you

**Comment by disnet** [comment]
Totally understandable! Thanks for giving it a try and helping out!

**Pull request closed without merging**
